### PR TITLE
Ignore unused files

### PR DESCRIPTION
**Pull request by TrySound**
Ref #81

### CODE REVIEW

**Comment by dylans** [comment]
Thanks @TrySound , not sure how we missed adding that previously to .gitignore!

**Comment by TrySound** [comment]
Is there something else to skip?

**Comment by dylans** [comment]
> Is there something else to skip?

I'm not sure I understand your question or comment. My remark was more hanging our head in shame that we hadn't made your PR part of the package sooner! Thanks again for your contribution.

**Comment by thetric** [comment]
@dylans The `typings` folder is gitignored, but still in Git. Shouldn't it be deleted, too?

**Comment by dylans** [comment]
Ah, yeah, it should have been done in the previous PR... that's what I get for landing a PR while traveling. :)

**Pull request merged**
