### PR TITLE
Avoid reading sourcemaps in js file if it is already in fileCoverage.inputSourceMap

### PR DESCRIPTION
**Pull request by mttcr**
From #123
PR #87 allowed to use the inputSourceMap provided in fileCoverage. The problem is that we still parse the js file to override the sourcemap if there is one inlined. This PR skips the reading of the js file if we already have the sourcemap.

### CODE REVIEW

**Comment by dylans** [comment]
@MichaReiser any chance you have a moment to review/test this proposed follow-up to #87?

**Comment by dylans** [comment]
@mttcr note this is failing with our tests, see https://travis-ci.org/SitePen/remap-istanbul/builds/190977909

**Comment by MichaReiser** [comment]
Probably not to test, but I can review it. Let me know when the tests are fixed.

**Comment by mttcr** [comment]
I restored the codeIsArray logic and I provided a test that checks that the CoverageTransformer correctly uses the provided inputSourceMap and not the one inlined in the source. To check that, the inputSourceMap is a bit different from the inlined one: it has a custom _sourceRoot_. The test passes with my branch, and doesn't with yours. 

@dylans @MichaReiser your tests are fixed and I also provided a new one to check the new functionality. Hope it's good for you!

**Comment by MichaReiser** [comment]
Looks good from my side...

**Comment by dylans** [comment]
Thanks @mttcr and @MichaReiser . I'll let this sit for a few days in case anyone else has thoughts or feedback, and then land it.

**Pull request merged**
