### PR TITLE
ignore mapping if line is not set

### PR DESCRIPTION
**Pull request by esskar**

### CODE REVIEW

**Comment by LuiSlacker** [comment]
Please approve, we also need this fix! Our Code coverage is broken unfortunately.

**Review by dylans — APPROVED** [review]

**Comment by esskar** [comment]
Thanks for the merge. May I ask you to publish a new version. Thanks.

**Comment by esskar** [comment]
@dylans  Hey, It has been a while. May I ask you to publish a new version, please.

**Comment by esskar** [comment]
Any chance this gets published as 0.14.0 ?

**Comment by fabripautasso** [comment]
@dylans @kitsonk @jdonaghue any chance we can get this fix released?

**Pull request merged**
