### PR TITLE
Bring through fnMap.decl and branchMap.loc when mapping nyc coverage files

### LINKED ISSUE #163: Remap loses `loc` and `decl` properties used by nyc reports
My source files collected using `nyc instrument` have json objects with `decl` properties in the `fnMap` and `loc` properties in the `branchMap`. After running through `remap-istanbul` both of these properties are lost and therefore `nyc report` chokes when trying to generate any details reports (html, lcov).

Source:

```js
{
	"project.js": {
		"path": "project.js",
		"fnMap": {
			"0": {
				"name": "locateBestProjectRoot",
				"decl": {
					"start": { "line": 6, "column": 9 },
					"end": { "line": 6, "column": 30 }
				},
				"loc": {
					"start": { "line": 6, "column": 39 },
					"end": { "line": 16, "column": 1 }
				},
				"line": 6
			}
		},
		"branchMap": {
			"0": {
				"loc": {
					"start": { "line": 7, "column": 4 },
					"end": { "line": 8, "column": 20 }
				},
				"type": "if",
				"locations": [
					{
						"start": { "line": 7, "column": 4 },
						"end": { "line": 8, "column": 20 }
					},
					{
						"start": { "line": 7, "column": 4 },
						"end": { "line": 8, "column": 20 }
					}
				],
				"line": 7
			}
		}
	}
}
```

Output:

```js
{
	"../../src/project.ts": {
		"path": "../../src/project.ts",
		"fnMap": {
			"1": {
				"name": "locateBestProjectRoot",
				"line": 6,
				"loc": {
					"start": { "line": 6, "column": 52 },
					"end": { "line": 18, "column": 1 }
				}
			}
		},
		"branchMap": {
			"1": {
				"line": 7,
				"type": "if",
				"locations": [
					{
						"start": { "line": 7, "column": 1 },
						"end": { "line": 8, "column": 14 }
					},
					{
						"start": { "line": 7, "column": 1 },
						"end": { "line": 8, "column": 14 }
					}
				]
			}
		}
	}
}
```

### PR DESCRIPTION
**Pull request by DanTup**
This fixes #163. Note: I'm a complete noob at this, so please check it over well to ensure I haven't broken anything (note: some of the tests fail for me locally without this change, so I couldn't test as thoroughly as I hoped).

Reasons for wanting this/discussion isn in #163.

### CODE REVIEW

**Comment by DanTup** [comment]
Travis is unhappy, but looks like the tests that failed are the same ones from my machine, which have failed for some previous builds?

**Comment by dylans** [comment]
@DanTup I think it looks like a reasonable fix. I've been pressed for time on this as we've been spending most of our time trying to get Dojo 2 out the door, hence the CI failures for previous builds. If you're happy with this, I'll go ahead and land it in master and plan to do a release sometime in the next week or so.

**Comment by DanTup** [comment]
@dylans That would be great! I believe with this fixed I'll finally be able to have detailed coverage reports 👍

**Comment by DanTup** [comment]
@dylans Please ping me once you do release this so I can upgrade and test (and set up my coverage reports :-))

**Comment by DanTup** [comment]
@dylans Do you think you'll have time to release this soon? Not a problem if not, but it'd be good to know if it's worth me getting a local copy into my repo so I can finish getting coverage working. Thanks!

**Comment by dylans** [comment]
@DanTup I'm working on it now, I've published 0.11.0, but for some reason, npm isn't yet showing the latest tag of 0.11.0.

**Comment by DanTup** [comment]
Weird.. I found this https://github.com/npm/npm/issues/6717 where someone reported the same and they said `npm view` will show the latest, but it's still on 0.10.1 :/

What happens if you try running `npm publish` again (set the version back in `package.json` first!)? Does it fail saying it's already there?

**Comment by dylans** [comment]
@DanTup yes, I was just trying that, and it fails `You cannot publish over the previously published versions: 0.11.0. : remap-istanbul`

**Comment by kip-dk** [comment]
When i try publish my package (kipon-xrmservice), i get email confirmation that it is done, but nothing happens on my npm package on npmjs.org. If i try do npm view kipon-xrmservice i get the old version (1.0.167). and if i try to republish, i get error that i cannot publis previosy published.

**Comment by DanTup** [comment]
Looks like npm is having problems :(

https://status.npmjs.org/incidents/gbk5bjx1169j

No indication whether it'll fix itself or not, but maybe worth checking back on that page in a few hours.

**Comment by dylans** [comment]
Thanks, I'll check back later!

**Comment by DanTup** [comment]
Looks like v0.11.0 has come through now, thank you! 👍

**Comment by kip-dk** [comment]
Thanks for the headsup. It also works in my for my library.

**Comment by DanTup** [comment]
It's on the website at least - can't get it via npm yet, but presumably it's making it's way through things. I'll try again in a bit, I'm sure it'll be there.

**Comment by kip-dk** [comment]
same problem here.. :-(

**Comment by DanTup** [comment]
0.11.0 came through now, I was able to update to it :-)

**Pull request merged**
