### PR TITLE
Add 'useAbsolutePaths' option

### PR DESCRIPTION
**Pull request by alexeibs**
'useAbsolutePaths' enforces using absolute paths in the output json file.
This is useful for combining coverage reports from different projects with istanbul-combine.

### CODE REVIEW

**Comment by kitsonk** [comment]
Thanks for the PR, we will take a look at it.

I tried to check to see if you had a [Contributors License Agreement](http://dojofoundation.org/about/cla) on file with us, but I can't find it under your GitHub username or e-mail.  CLAs are really important to us and they are quick to fill out.  If you already have one on file, just let me know the details.

**Comment by alexeibs** [comment]
I have signed the CLA

**Comment by kitsonk** [comment]
> Alexei Bykov submitted a CLA on 2015-12-11 18:54:48.

**Comment by kitsonk** [comment]
Merged via 32e2a1e37410a4bfc53a2e1e32d73b205a976bfb

**Pull request closed without merging**
