### PR TITLE
Drop dependency on deprecated `gulp-util`

### PR DESCRIPTION
**Pull request by demurgos**
Closes SitePen/remap-istanbul#157

### CODE REVIEW

**Comment by dylans** [comment]
Thanks @demurgos!

**Comment by simonua** [comment]
Hi @dylans, would you happen to have an idea when a subsequent remap-istanbul release will go out? Thank you!

**Comment by dylans** [comment]
> Hi @dylans, would you happen to have an idea when a subsequent remap-istanbul release will go out, please? Thank you!

hopefully next week!

**Comment by demurgos** [comment]
Could you post a message here once it's published? It would help me with tracking the ecosystem migration.

**Comment by dylans** [comment]
@simonua @demurgos remap-istanbul 0.10.0 has been tagged and published to npm. I'm going to open a separate issue to update some of the other stable dependencies.

**Comment by simonua** [comment]
Thank you, @dylans! Updating now...

**Pull request merged**
