### PR TITLE
Add exclude option to command line interface

### PR DESCRIPTION
**Pull request by CookPete**
A result of https://github.com/SitePen/remap-istanbul/pull/30#issuecomment-195393171, this adds the same exclude functionality to the CLI, albeit in a rather crude way.

### CODE REVIEW

**Comment by CookPete** [comment]
Rebased on latest `master`.

**Comment by kitsonk** [comment]
@CookPete thanks for the PR.  I have looked and will be glad to merge it.  I haven't been able to find an CLA for you though on the [Dojo Foundation](http://dojofoundation.org/about/cla).  If you have one could you let me know, or if you have one with the [jQuery Foundation](https://contribute.jquery.org/CLA/) that would work too.

**Comment by CookPete** [comment]
@kitsonk I've just filled one out with `pete [at] cookpete [dot] com`

**Comment by CookPete** [comment]
@kitsonk Hold fire whilst I add the new CLI option to the readme.

**Comment by CookPete** [comment]
> Hold fire whilst I add the new CLI option to the readme.

Done.

**Comment by kitsonk** [comment]
```
Pete Cook submitted a CLA on 2016-04-15 13:51:11.
```

**Pull request merged**
