### PR TITLE
allow options.exclude to be a function

### LINKED ISSUE #99: Allow custom function for exclude option
This might be easier to do before #98 and would give us much more flexibility to control which files we exclude.

### PR DESCRIPTION
**Pull request by ianstarz**
This closes #99

### CODE REVIEW

**Comment by ianstarz** [comment]
Added test, not sure how to rerun coverage

**Comment by jdonaghue** [comment]
This looks great @ianstarz thanks for your work! Landing this now.

**Comment by ianstarz** [comment]
Sure thing! Happy to help. Updated the readme in #101. Are you guys planning on releasing a 0.7.1 before releasing 0.8.0?

**Comment by dylans** [comment]
@ianstarz I think we have enough to just go to 0.8.0 very soon now.

**Pull request merged**
