### PR TITLE
Don't Attempt to Remap Invalid Line/Column Offsets

### PR DESCRIPTION
**Pull request by steve-gray**
Some babel transforms leave lines in the sourcemap with no origin lines, causing attempts to remap them with the sourcemap npm module to fail with an error such as:

https://github.com/SitePen/remap-istanbul/issues/57

This change avoids attempting to remap source lines where we know the line identifier is invalid, allowing the coverage to continue to process.

### CODE REVIEW

**Comment by steve-gray** [comment]
For reference if anyone was interested, the offending babel plugins are:

      "babel": {
        "presets": [
          "es2015",
          "stage-1"
        ],
        "plugins": [
          "add-module-exports",
          "transform-es2015-modules-commonjs",
          "syntax-export-extensions"
        ]
      },

(Extract from package.json). One of these three (my code needs all three unfortunately, so can't tell which), causes a reasonably basic script to error.

**Comment by steve-gray** [comment]
Changed the code to deal with more cases, undoing my original and doing something else - because I've now got examples on-hand where offsets for columns such as 'col: -14' get written out in the sourcemaps. I've looked at how remap.js is dealing with these other errant cases and decided just to make these changes consistent with those, though I've left my added test case in because it'll help detect a reversion in this area.

When merging, just squash the commits.

**Comment by kitsonk** [comment]
I really hate to be a pest, but we are strict about CLAs.  I checked the [Dojo Foundation](http://dojofoundation.org/about/cla) and couldn't find you username or e-mail used in the PR.  If you have one, could you let me know what username it is under.  If you have one with the jQuery foundation that works as well.

**Comment by steve-gray** [comment]
Done. Dojo username Steve-gray

**Pull request merged**
