### PR TITLE
fix relative paths handling in sourcemaps (issue #70)

### PR DESCRIPTION
**Pull request by zxbodya**

### CODE REVIEW

**Comment by gitawego** [comment]
hope this could be merged :)

**Comment by zxbodya** [comment]
btw, I have forked the project, and done a lot of refactoring there(above fixing this), if you are interested: https://github.com/zxbodya/istanbul-sourcemap-report

**Comment by gitawego** [comment]
thanks, gonna try yours. but I hope the community isn't diverged.

**Comment by zxbodya** [comment]
it looks there is already official istanbuljs solution, that is going to replace both this projects - https://github.com/istanbuljs/nyc :) 

realised that after doing fork…

**Comment by jdonaghue** [comment]
Apologies for the long delay in activity on this project, I am planning on
reviewing and/or landing a bunch of the outstanding PR's this week.

Thanks!

**Comment by gitawego** [comment]
nice too know ^^ thanks in advance

**Comment by jdonaghue** [comment]
Thanks for doing this!

**Pull request merged**
