### PR TITLE
Option to override sources root path.

### PR DESCRIPTION
**Pull request by arma-gast**

### CODE REVIEW

**Comment by kitsonk** [comment]
Also, I am about to add the contributing guidelines.  We care passionately about Open Source and one of things we enforce is that all contributions are covered by a CLA.  I checked and couldn't find a CLA for you based on your GitHub username.  Could you take a moment and complete a [CLA](http://dojofoundation.org/about/claForm) or let me know what username/e-mail/org that covers this contribution.

**Comment by arma-gast** [comment]
Filled CLA form.

**Comment by kitsonk** [comment]
Aleksey Blokhin submitted a CLA on 2015-09-11 10:34:37.

**Comment by kitsonk** [comment]
Merged via 5ff38d980eb7f2deca5b4e1c3de211c6be7732b3

**Pull request closed without merging**
